/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import Link from "next/link";

export default function Custom404() {
  return (
    <>
      <Head>
        <title>404 | Mohi Khashan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen flex font-mono">
        <div className="flex flex-col justify-center items-stretch max-w-2xl mx-8 md:mx-auto mb-16">
          <h1 className="font-bold text-2xl md:text-3xl text-justify tracking-tight mb-4 text-black dark:text-white">
            404 – Nothing Found at this path 😵‍💫
          </h1>
          <p className="text-gray-600 dark:text-gray-400 mb-8 text-justify">
            Why show a generic 404 when I can make it sound mysterious? It seems
            you've found something that used to exist, or you spelled something
            wrong. I'm guessing you spelled something wrong. Can you double
            check that URL?
          </p>
          <Link
            href="/"
            className="p-1 sm:p-4 w-64 font-bold mx-auto bg-orange-500 text-center rounded-md text-black dark:text-white"
          >
            Return Home
          </Link>
        </div>
      </main>
    </>
  );
}
