import Head from 'next/head'

export default function Custom500() {
  return (
    <>
      <Head>
        <title>500 | Mohi Khashan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>500 - Page Not Found</h1>
      </main>
    </>
  )
}
