import Head from 'next/head'
import Link from 'next/link';

import { getCategories, getPostsData } from '@/lib/api';
import { InferGetStaticPropsType } from 'next';

export default function HomePage({ posts, projects }: InferGetStaticPropsType<typeof getStaticProps>) {
  return (
    <>
      <Head>
        <title>Home | Mo Khashan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <div className="space-y-6">
      <div className="space-y-8 text-white">

        <div className="mt-12 max-w-screen-md space-y-4">
          <div className="inline-flex">
            <h1 className="text-4xl md:text-6xl font-semibold text-white">Mo Khashan <span className="text-3xl cursor-pointer">🗣️</span></h1>
          </div>
          <p className="text-zinc-500 text-xl md:text-2xl text-left">
            Front-end Engineer interested in how technology can enhance 
            intuition and creativity. 
            Experienced with <span className="text-orange-500">Javascript</span>, <span className="text-orange-500">Typescript</span>, <span className="text-orange-500">React</span>, <span className="text-orange-500">Next</span>, <span className="text-orange-500">React Native</span> and <span className="text-orange-500">HTML/CSS</span>
            .
          </p>
          <p className="text-zinc-500 text-2xl">
            As a 🥷 I&apos;ve built, developed and shipped 10+ products (with over +100K users).
          </p>
        </div>

        <div className="mt-22 max-w-screen-md space-y-4">
          <h1 className="md:text-2xl font-semibold text-orange-500">Recent Blog Posts</h1>
          <div className="flex flex-col divide-y-[1px] divide-zinc-700">
            {posts.map((post: any) => 
              <Link 
                key={post.slug}
                href={{
                  pathname: '/blog/[slug]',
                  query: { slug: post.slug },
                }}
                className="flex flex-row py-4 justify-between hover:text-orange-500">
                <div>{post.title}</div>
                <div className="text-zinc-500">
                  {post.categories.map((category: any) => (category.name))}
                </div>
              </Link>
            )}
          </div>
        </div>

        <div className="mt-22 max-w-screen-md space-y-4">
          <h1 className="md:text-2xl font-semibold text-orange-500">Featured Projects</h1>
          <div className="flex-col space-y-2">
            {projects.map((project: any) => 
              <Link
                href={`/`}
                key={project}
                className="block space-y-1.5 rounded-lg border border-white/10 px-4 py-3 hover:border-white/20 bg-zinc-800"
              >
              <div>{project.name}</div>
              <div className="line-clamp-3 text-sm text-zinc-400">
                {project.slug}
              </div>
            </Link>
            )}
            {!projects.length && (<div>No Project found.</div>)}
          </div>
        </div>
        
      </div>
    </div>
      </main>
    </>
  )
}

export async function getStaticProps() {
  const butterToken = process.env.NEXT_PUBLIC_BUTTER_CMS_API_KEY

  if (butterToken) {
    try {
      const blogPosts = (await getPostsData()).posts
      const projects = await getCategories()

      return { props: { posts: blogPosts, projects } }
    } catch (e) {
      console.log("Could not get posts", e);

      return {
        props: {
          posts: [],
          projects: []
        }
      }
    }
  }
  
}